export const offsets = [
	{
		offset: 0x0,
		size: 8,
		key: ['itemEquipped'],
		bits: {
			0: ['variaSuit'],
			1: ['springBall'],
			2: ['morphBall'],
			3: ['screwAttack'],
			5: ['gravitySuit'],
		},
	},
	{
		offset: 0x1,
		size: 8,
		key: ['itemEquipped'],
		bits: {
			highJumpBoots: 0,
			spaceJump: 1,
			bombs: 2,
			speedBooster: 5,
			grapplingBeam: 6,
			xRayScope: 7,
		},
	},
	{
		offset: 0x2,
		size: 8,
		key: ['itemInInventory'],
		bits: {
			0: ['variaSuit'],
			1: ['springBall'],
			2: ['morphBall'],
			3: ['screwAttack'],
			5: ['gravitySuit'],
		},
	},
	{
		offset: 0x3,
		size: 8,
		key: ['itemInInventory'],
		bits: {
			0: ['highJumpBoots'],
			1: ['spaceJump'],
			3: ['bombs'],
			5: ['speedBooster'],
			6: ['grapplingBeam'],
			7: ['xRayScope'],
		},
	},
	{
		offset: 0x4,
		size: 8,
		key: ['itemEquipped'],
		bits: {
			0: ['waveBeam'],
			1: ['iceBeam'],
			2: ['spazer'],
			3: ['plazmaBeam'],
		},
	},
	{
		offset: 0x5,
		size: 8,
		key: ['itemEquipped'],
		bits: {
			4: ['chargeBeam'],
		},
	},
	{
		offset: 0x6,
		size: 8,
		key: ['itemInInventory'],
		bits: {
			0: ['waveBeam'],
			1: ['iceBeam'],
			2: ['spazer'],
			3: ['plasmaBeam'],
		},
	},
	{
		offset: 0x7,
		size: 8,
		key: ['itemInInventory'],
		bits: {
			4: ['chargeBeam'],
		},
	},
	{
		offset: 0x10,
		size: 16,
		key: ['config', 'shotButton'],
	},
	{
		offset: 0x12,
		size: 16,
		key: ['config', 'jumpButton'],
	},
	{
		offset: 0x14,
		size: 16,
		key: ['config', 'dashButton'],
	},
	{
		offset: 0x16,
		size: 16,
		key: ['config', 'itemCancelButton'],
	},
	{
		offset: 0x18,
		size: 16,
		key: ['config', 'itemSelectButton'],
	},
	{
		offset: 0x1a,
		size: 16,
		key: ['config', 'angleDownButton'],
	},
	{
		offset: 0x1c,
		size: 16,
		key: ['config', 'angleUputton'],
	},
	{
		offset: 0x20,
		size: 16,
		key: ['currentEnergy'],
	},
	{
		offset: 0x22,
		size: 16,
		key: ['maxEnergy'],
	},
	{
		offset: 0x24,
		size: 16,
		key: ['currentMissiles'],
	},
	{
		offset: 0x26,
		size: 16,
		key: ['maxMissiles'],
	},
	{
		offset: 0x28,
		size: 16,
		key: ['currentSuperMissiles'],
	},
	{
		offset: 0x2a,
		size: 16,
		key: ['maxSuperMissiles'],
	},
	{
		offset: 0x32,
		size: 16,
		key: ['maxReserveEnergy'],
	},
	{
		offset: 0x34,
		size: 16,
		key: ['reserveEnergy'],
	},
	{
		offset: 0x3e,
		size: 8,
		key: ['gameTime', 'Hours'],
	},
	{
		offset: 0x3c,
		size: 8,
		key: ['gameTime', 'Minutes'],
	},
	{
		offset: 0x40,
		size: 8,
		key: ['config', 'language'],
		bits: {
			0: ['englishOrJapanese'],
		},
	},
	{
		offset: 0x42,
		size: 8,
		key: ['config', 'moonwalk'],
		bits: {
			0: ['moonwalkOffOrOn'],
		},
	},
	{
		offset: 0x48,
		size: 8,
		key: ['config', 'icon cancel'],
		bits: {
			0: ['iconCancelManualOrAutomatic'],
		},
	},
	{
		offset: 0x60,
		size: 8,
		key: ['bossStatueBroken', 'zebetites'],
		bits: {
			0: ['zebetiteBit0'],
			1: ['zebetiteBit1'],
			2: ['zebetiteBit2'],
			6: ['bossStatueBroken', 'phantoon'],
			7: ['bossStatueBroken', 'ridley'],
		},
	},
	{
		offset: 0x61,
		size: 8,
		key: ['bossStatueBroken', 'landmark'],
		bits: {
			0: ['bossStateuBroken', 'draygon'],
			1: ['bossStateuBroken', 'kraid'],
			2: ['landmark', 'tourian', 'elevator'],
			3: ['landmark', 'maridia', 'glassTubeBroken'],
			7: ['landmark', 'rescuedAnimals'],
		},
	},
	{
		offset: 0x62,
		size: 8,
		key: ['metroidRooms'],
		bits: {
			0: ['metroidRoom0'],
			1: ['metroidRoom1'],
			2: ['metroidRoom2'],
			3: ['metroidRoom3'],
		},
	},
	{
		offset: 0x68,
		size: 8,
		key: ['bossDefeated'],
		bits: {
			2: ['bossDefeated', 'silverTorizo'],
		},
	},
	{
		offset: 0x69,
		size: 8,
		key: ['bossDefeated'],
		bits: {
			0: ['bossDefeated', 'kraid'],
			1: ['bossDefeated', 'sporeSpawn'],
		},
	},
	{
		offset: 0x6a,
		size: 8,
		key: ['bossDefeated'],
		bits: {
			0: ['bossDefeated', 'ridley'],
			1: ['bossDefeated', 'crocomire'],
			2: ['bossDefeated', 'goldenTorizo'],
		},
	},
	{
		offset: 0x6b,
		size: 8,
		key: ['bossDefeated'],
		bits: {
			0: ['bossDefeated', 'phantoon'],
		},
	},
	{
		offset: 0x6c,
		size: 8,
		key: ['bossDefeated'],
		bits: {
			0: ['bossDefeated', 'draygon'],
			1: ['bossDefeated', 'botwoon'],
		},
	},
	{
		offset: 0xb0,
		size: 8,
		key: ['itemAcquired', 'crateria', 'missilePacks', 'powerBombPacks'],
		bits: {
			0: ['crateria', 'powerBombPack'],
			1: ['crateria', 'missilePack'],
			2: ['crateria', 'missilePack'],
			3: ['crateria', 'missilePack'],
			4: ['crateria', 'missilePack'],
			6: ['crateria', 'missilePack'],
			7: ['crateria', 'bombPack'],
		},
	},
	{
		offset: 0xb1,
		size: 8,
		key: ['crateria', 'brinstar', 'missilePacks', 'superMissilePacks'],
		bits: {
			1: ['crateria', 'missilePack'],
			2: ['crateria', 'missilePack'],
			3: ['crateria', 'superMissilePack'],
			4: ['crateria', 'missilePack'],
			6: ['brinstar', 'superMissilePack'],
			7: ['brinstar', 'missilePack'],
		},
	},
	{
		offset: 0xb2,
		size: 8,
		key: ['itemAcquired', 'brinstar', 'missilePacks', 'superMissilePacks'],
		bits: {
			0: ['brinstar', 'superMissilePack'],
			2: ['brinstar', 'missilePack'],
			3: ['brinstar', 'missilePack'],
			5: ['brinstar', 'missilePack'],
			6: ['brinstar', 'missilePack'],
			7: ['itemAcquired', 'chargeBeam'],
		},
	},
	{
		offset: 0xb3,
		size: 8,
		key: ['itemAcquired', 'brinstar', 'missilePacks', 'superMissilePacks'],
		bits: {
			1: ['brinstar', 'missilePack'],
			2: ['itemAcquired', 'morphBall'],
			4: ['brinstar', 'missilePack'],
			7: ['brinstar', 'superMissilePack'],
		},
	},
	{
		offset: 0xb4,
		size: 8,
		key: ['itemAcquired', 'brinstar', 'missilePacks'],
		bits: {
			2: ['brinstar', 'missilePack'],
			4: ['brinstar', 'missilePack'],
			5: ['brinstar', 'missilePack'],
			6: ['itemAcquired', 'xRayScope'],
		},
	},
	{
		offset: 0xb5,
		size: 8,
		key: ['itemAcquired', 'brinstar', 'missilePacks'],
		bits: {
			1: ['brinstar', 'missilePack'],
			2: ['itemAcquired', 'spazer'],
			4: ['brinstar', 'missilePack'],
		},
	},
	{
		offset: 0xb6,
		size: 8,
		key: ['itemAcquired', 'norfair', 'missilePacks'],
		bits: {
			0: ['itemAcquired', 'variaSuit'],
			1: ['norfair', 'missilePack'],
			2: ['itemAcquired', 'iceBeam'],
			3: ['norfair', 'missilePack'],
			5: ['itemAcquired', 'highJumpBoots'],
			6: ['norfair', 'missilePack'],
			7: ['norfair', 'missilePack'],
		},
	},
	{
		offset: 0xb7,
		size: 8,
		key: ['norfair', 'missilePacks'],
		bits: {
			2: ['norfair', 'missilePack'],
			3: ['norfair', 'missilePack'],
			6: ['norfair', 'missilePack'],
			7: ['norfair', 'missilePack'],
		},
	},
	{
		offset: 0xb8,
		size: 8,
		key: ['norfair', 'missilePacks', 'superMissilePacks'],
		bits: {
			0: ['norfair', 'missilePack'],
			1: ['norfair', 'missilePack'],
			3: ['norfair', 'missilePack'],
			6: ['norfair', 'missilePack'],
			7: ['norfair', 'superMissilePack'],
		},
	},
	{
		offset: 0xb9,
		size: 8,
		key: ['itemAcquired', 'norfair', 'missilePacks'],
		bits: {
			1: ['norfair', 'missilePack'],
			2: ['norfair', 'missilePack'],
			5: ['norfair', 'missilePack'],
			7: ['itemAcquired', 'screwAttack'],
		},
	},
	{
		offset: 0xb7,
		size: 8,
		key: ['itemAcquired'],
		bits: {
			4: ['itemAcquired', 'grapplingBeam'],
		},
	},
	{
		offset: 0xb8,
		size: 8,
		key: ['itemAcquired'],
		bits: {
			2: ['itemAcquired', 'speedBooster'],
			4: ['itemAcquired', 'waveBeam'],
		},
	},
	{
		offset: 0xb9,
		size: 8,
		key: ['itemAcquired'],
		bits: {
			7: ['itemAcquired', 'screwAttack'],
		},
	},
	{
		offset: 0xc0,
		size: 8,
		key: ['itemAcquired', 'wreckedShip', 'missilePacks', 'superMissilePacks'],
		bits: {
			0: ['wreckedShip', 'missilePack'],
			2: ['wreckedShip', 'missilePack'],
			3: ['wreckedShip', 'missilePack'],
			5: ['wreckedShip', 'superMissilePack'],
			6: ['wreckedShip', 'superMissilePack'],
			7: ['itemAcquired', 'gravitySuit'],
		},
	},
	{
		offset: 0xc1,
		size: 8,
		key: ['itemAcquired', 'maridia', 'missilePacks', 'superMissilePacks'],
		bits: {
			0: ['maridia', 'missilePack'],
			1: ['maridia', 'superMissilePack'],
			3: ['maridia', 'missilePack'],
			4: ['maridia', 'superMissilePack'],
			5: ['maridia', 'missilePack'],
			6: ['maridia', 'missilePack'],
			7: ['itemAcquired', 'plasmaBeam'],
		},
	},
	{
		offset: 0xc2,
		size: 8,
		key: ['itemAcquired', 'maridia', 'missilePacks', 'superMissilePacks'],
		bits: {
			0: ['maridia', 'missilePack'],
			2: ['maridia', 'missilePack'],
			4: ['maridia', 'missilePack'],
			5: ['maridia', 'superMissilePack'],
			6: ['itemAcquired', 'springBall'],
			7: ['maridia', 'missilePack'],
		},
	},
	{
		offset: 0xc3,
		size: 8,
		key: ['itemAcquired'],
		bits: {
			2: ['itemAcquired', 'spaceJump'],
		},
	},
	{
		offset: 0x148,
		size: 8,
		key: ['crateria', 'map'],
	},
	{
		offset: 0x149,
		size: 8,
		key: ['brinstar', 'map'],
	},
	{
		offset: 0x14a,
		size: 8,
		key: ['norfair', 'map'],
	},
	{
		offset: 0x14b,
		size: 8,
		key: ['wreckedShip', 'map'],
	},
	{
		offset: 0x14c,
		size: 8,
		key: ['maridia', 'map'],
	},
	{
		offset: 0x14d,
		size: 8,
		key: ['tourian', 'map'],
	},
	{
		offset: 0x156,
		size: 8,
		key: ['save spot', 'point'],
	},
	{
		offset: 0x158,
		size: 8,
		key: ['save spot', 'area'],
	},
] as const;
